module.exports = [
  { codigo: 'bitcoin', nome: 'Bitcoin', preco: 0, quantidade: 0 },
  { codigo: 'ethereum', nome: 'Ethereum', preco: 0, quantidade: 0 },
  { codigo: 'tether', nome: 'Tether', preco: 0, quantidade: 0 },
  { codigo: 'binancecoin', nome: 'BNB', preco: 0, quantidade: 0 },
  { codigo: 'solana', nome: 'Solana', preco: 0, quantidade: 0 },
  { codigo: 'usd-coin', nome: 'USD Coin', preco: 0, quantidade: 0 },
  { codigo: 'staked-ether', nome: 'Lido Staked Ether', preco: 0, quantidade: 0 },
  { codigo: 'dogecoin', nome: 'Dogecoin', preco: 0, quantidade: 0 },
  { codigo: 'tron', nome: 'TRON', preco: 0, quantidade: 0 },
  { codigo: 'cardano', nome: 'Cardano', preco: 0, quantidade: 0 },
  { codigo: 'wrapped-steth', nome: 'Wrapped stETH', preco: 0, quantidade: 0 },
  { codigo: 'chainlink', nome: 'Chainlink', preco: 0, quantidade: 0 },
  { codigo: 'wrapped-beacon-eth', nome: 'Wrapped Beacon ETH', preco: 0, quantidade: 0 },
  { codigo: 'wrapped-bitcoin', nome: 'Wrapped Bitcoin', preco: 0, quantidade: 0 },
  { codigo: 'ethena-usde', nome: 'Ethena USDe', preco: 0, quantidade: 0 },
  { codigo: 'figure-heloc', nome: 'Figure Heloc', preco: 0, quantidade: 0 },
  { codigo: 'hyperliquid', nome: 'Hyperliquid', preco: 0, quantidade: 0 },
  { codigo: 'sui', nome: 'Sui', preco: 0, quantidade: 0 },
  { codigo: 'wrapped-eeth', nome: 'Wrapped eETH', preco: 0, quantidade: 0 },
  { codigo: 'bitcoin-cash', nome: 'Bitcoin Cash', preco: 0, quantidade: 0 },
  { codigo: 'stellar', nome: 'Stellar', preco: 0, quantidade: 0 },
  { codigo: 'avalanche-2', nome: 'Avalanche', preco: 0, quantidade: 0 },
  { codigo: 'weth', nome: 'WETH', preco: 0, quantidade: 0 },
  { codigo: 'hedera', nome: 'Hedera', preco: 0, quantidade: 0 },
  { codigo: 'leo-token', nome: 'LEO Token', preco: 0, quantidade: 0 },
  { codigo: 'cronos', nome: 'Cronos', preco: 0, quantidade: 0 },
  { codigo: 'litecoin', nome: 'Litecoin', preco: 0, quantidade: 0 },
  { codigo: 'toncoin', nome: 'Toncoin', preco: 0, quantidade: 0 },
  { codigo: 'usds', nome: 'USDS', preco: 0, quantidade: 0 },
  { codigo: 'shiba-inu', nome: 'Shiba Inu', preco: 0, quantidade: 0 },
  { codigo: 'binance-usd', nome: 'Binance USD', preco: 0, quantidade: 0 },
  { codigo: 'world-liberty-financial', nome: 'World Liberty Financial', preco: 0, quantidade: 0 },
  { codigo: 'coinbase-wrapped-btc', nome: 'Coinbase Wrapped BTC', preco: 0, quantidade: 0 },
  { codigo: 'whitebit', nome: 'WhiteBIT Coin', preco: 0, quantidade: 0 },
  { codigo: 'bitget-token', nome: 'Bitget Token', preco: 0, quantidade: 0 },
  { codigo: 'polkadot', nome: 'Polkadot', preco: 0, quantidade: 0 },
  { codigo: 'uniswap', nome: 'Uniswap', preco: 0, quantidade: 0 },
  { codigo: 'ethena-staked-usde', nome: 'Ethena Staked USDe', preco: 0, quantidade: 0 },
  { codigo: 'monero', nome: 'Monero', preco: 0, quantidade: 0 },
  { codigo: 'aave', nome: 'Aave', preco: 0, quantidade: 0 },
  { codigo: 'dai', nome: 'Dai', preco: 0, quantidade: 0 },
  { codigo: 'ethena', nome: 'Ethena', preco: 0, quantidade: 0 },
  { codigo: 'pepe', nome: 'Pepe', preco: 0, quantidade: 0 },
  { codigo: 'mantle', nome: 'Mantle', preco: 0, quantidade: 0 },
  { codigo: 'okb', nome: 'OKB', preco: 0, quantidade: 0 },
  { codigo: 'ethereum-classic', nome: 'Ethereum Classic', preco: 0, quantidade: 0 },
  { codigo: 'jito-staked-sol', nome: 'Jito Staked SOL', preco: 0, quantidade: 0 },
  { codigo: 'bittensor', nome: 'Bittensor', preco: 0, quantidade: 0 },
  { codigo: 'pol', nome: 'POL (ex-MATIC)', preco: 0, quantidade: 0 }
];
