module.exports = [
  // 45 principais ações da B3
  { codigo: 'PETR4', nome: 'Petrobras PN', preco: 0, quantidade: 0 },
  { codigo: 'VALE3', nome: 'Vale ON', preco: 0, quantidade: 0 },
  { codigo: 'ITUB4', nome: 'Itaú Unibanco PN', preco: 0, quantidade: 0 },
  { codigo: 'BBDC4', nome: 'Bradesco PN', preco: 0, quantidade: 0 },
  { codigo: 'ABEV3', nome: 'Ambev ON', preco: 0, quantidade: 0 },
  { codigo: 'BBAS3', nome: 'Banco do Brasil ON', preco: 0, quantidade: 0 },
  { codigo: 'WEGE3', nome: 'Weg ON', preco: 0, quantidade: 0 },
  { codigo: 'B3SA3', nome: 'B3 ON', preco: 0, quantidade: 0 },
  { codigo: 'RENT3', nome: 'Localiza ON', preco: 0, quantidade: 0 },
  { codigo: 'JBSS3', nome: 'JBS ON', preco: 0, quantidade: 0 },
  { codigo: 'SUZB3', nome: 'Suzano ON', preco: 0, quantidade: 0 },
  { codigo: 'GGBR4', nome: 'Gerdau PN', preco: 0, quantidade: 0 },
  { codigo: 'CSNA3', nome: 'CSN ON', preco: 0, quantidade: 0 },
  { codigo: 'ELET3', nome: 'Eletrobras ON', preco: 0, quantidade: 0 },
  { codigo: 'ELET6', nome: 'Eletrobras PNB', preco: 0, quantidade: 0 },
  { codigo: 'BRFS3', nome: 'BRF ON', preco: 0, quantidade: 0 },
  { codigo: 'HAPV3', nome: 'Hapvida ON', preco: 0, quantidade: 0 },
  { codigo: 'LREN3', nome: 'Lojas Renner ON', preco: 0, quantidade: 0 },
  { codigo: 'RADL3', nome: 'Raia Drogasil ON', preco: 0, quantidade: 0 },
  { codigo: 'NTCO3', nome: 'Natura ON', preco: 0, quantidade: 0 },
  { codigo: 'CYRE3', nome: 'Cyrela ON', preco: 0, quantidade: 0 },
  { codigo: 'MRVE3', nome: 'MRV ON', preco: 0, quantidade: 0 },
  { codigo: 'UGPA3', nome: 'Ultrapar ON', preco: 0, quantidade: 0 },
  { codigo: 'VIVT3', nome: 'Vivo ON', preco: 0, quantidade: 0 },
  { codigo: 'TIMS3', nome: 'TIM ON', preco: 0, quantidade: 0 },
  { codigo: 'CCRO3', nome: 'CCR ON', preco: 0, quantidade: 0 },
  { codigo: 'CMIG4', nome: 'Cemig PN', preco: 0, quantidade: 0 },
  { codigo: 'CPLE6', nome: 'Copel PNB', preco: 0, quantidade: 0 },
  { codigo: 'TAEE11', nome: 'Taesa Units', preco: 0, quantidade: 0 },
  { codigo: 'ENEV3', nome: 'Eneva ON', preco: 0, quantidade: 0 },
  { codigo: 'PRIO3', nome: 'PetroRio ON', preco: 0, quantidade: 0 },
  { codigo: 'SLCE3', nome: 'SLC Agrícola ON', preco: 0, quantidade: 0 },
  { codigo: 'BRML3', nome: 'BR Malls ON', preco: 0, quantidade: 0 },
  { codigo: 'EZTC3', nome: 'EZTEC ON', preco: 0, quantidade: 0 },
  { codigo: 'CVCB3', nome: 'CVC ON', preco: 0, quantidade: 0 },
  { codigo: 'YDUQ3', nome: 'Yduqs ON', preco: 0, quantidade: 0 },
  { codigo: 'SOMA3', nome: 'Grupo Soma ON', preco: 0, quantidade: 0 },
  { codigo: 'PETZ3', nome: 'Petz ON', preco: 0, quantidade: 0 },
  { codigo: 'ALPA4', nome: 'Alpargatas PN', preco: 0, quantidade: 0 },
  { codigo: 'CRFB3', nome: 'Carrefour ON', preco: 0, quantidade: 0 },
  { codigo: 'MGLU3', nome: 'Magazine Luiza ON', preco: 0, quantidade: 0 },
  { codigo: 'AMER3', nome: 'Americanas ON', preco: 0, quantidade: 0 },
  { codigo: 'COGN3', nome: 'Cogna ON', preco: 0, quantidade: 0 },
  { codigo: 'BEEF3', nome: 'Minerva ON', preco: 0, quantidade: 0 },
  // 5 criptos
  { codigo: 'BTC', nome: 'Bitcoin', preco: 0, quantidade: 0 },
  { codigo: 'ETH', nome: 'Ethereum', preco: 0, quantidade: 0 },
  { codigo: 'SUI', nome: 'Sui', preco: 0, quantidade: 0 },
  { codigo: 'KAMINO', nome: 'Kamino', preco: 0, quantidade: 0 },
  { codigo: 'ENA', nome: 'Ena', preco: 0, quantidade: 0 }
];
